# Generated by Django 3.1.4 on 2021-02-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210228_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Complete_this_order',
            field=models.BooleanField(default=False),
        ),
    ]
